### ISSUE TITLE
Read Timeout Error

### ISSUE THREAD

**Issue by clayms** [xtream1101/s3-concat#17]
I am getting a lot of `ReadTimeoutError`s.  Not sure why the `endpoint URL` is `"None"`. 

Is there a setting that I can change to limit eliminate the occurrence of this error?

```python
CRITICAL:s3_concat.multipart_upload_job:Read timeout on endpoint URL: "None": When getting my/s3/prefix/my-file.json from the bucket my-s3-bucket
ERROR:s3_concat.utils:Retry failed batch of: [5, (5, [('my/s3/prefix/my-file-01.json', 343575), ('my/s3/prefix/my-file-02.json', 531245), ... ])]
Traceback (most recent call last):
  File "/opt/env/lib/python3.7/site-packages/urllib3/response.py", line 443, in _error_catcher
    yield
  File "/opt/env/lib/python3.7/site-packages/urllib3/response.py", line 566, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/opt/env/lib/python3.7/site-packages/urllib3/response.py", line 532, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/local/lib/python3.7/http/client.py", line 478, in read
    s = self._safe_read(self.length)
  File "/usr/local/lib/python3.7/http/client.py", line 628, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/env/lib/python3.7/site-packages/botocore/response.py", line 99, in read
    chunk = self._raw_stream.read(amt)
  File "/opt/env/lib/python3.7/site-packages/urllib3/response.py", line 592, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/env/lib/python3.7/site-packages/urllib3/response.py", line 448, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: AWSHTTPSConnectionPool(host='ucc-filings-results-prod.s3.amazonaws.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/env/lib/python3.7/site-packages/s3_concat/utils.py", line 19, in _thread_run
    response = callback(item)
  File "/opt/env/lib/python3.7/site-packages/s3_concat/multipart_upload_job.py", line 108, in get_small_parts
    )['Body'].read()
  File "/opt/env/lib/python3.7/site-packages/botocore/response.py", line 102, in read
    raise ReadTimeoutError(endpoint_url=e.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "None"

```

**Comment by xtream1101** [comment]
endpoint url being `None` means it will be using amazon's s3 service. As for the timeouts I am not sure as I cannot reproduce the error and my be a boto3 configuration or network issue.
